name: Conventional Commits

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
